
FIND_PATH(MAPSERVER_INCLUDE_DIR
    NAMES mapserver.h
    PATH_SUFFIXES mapserver
)

FIND_LIBRARY(MAPSERVER_LIBRARY
    NAMES mapserver
)

set(MAPSERVER_INCLUDE_DIRS ${MAPSERVER_INCLUDE_DIR})
set(MAPSERVER_LIBRARIES ${MAPSERVER_LIBRARY})
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MAPSERVER DEFAULT_MSG MAPSERVER_LIBRARY MAPSERVER_INCLUDE_DIR)
mark_as_advanced(MAPSERVER_LIBRARY MAPSERVER_INCLUDE_DIR)
