set(LMDB_FOUND TRUE)

set(LMDB_INC_SEARCH_PATH "/usr/include")
set(LMDB_LIB_SEARCH_PATH "/usr/lib")

find_path(LMDB_INCLUDE_DIR NAMES  "lmdb.h" HINTS ${LMDB_INC_SEARCH_PATH})
find_library(LMDB_LIBRARY NAMES "lmdb" HINTS ${LMDB_LIB_SEARCH_PATH})

set(LMDB_INCLUDE_DIRS ${LMDB_INCLUDE_DIR})
set(LMDB_LIBRARIES ${LMDB_LIBRARY})
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LMDB DEFAULT_MSG LMDB_LIBRARY LMDB_INCLUDE_DIR)
mark_as_advanced(LMDB_LIBRARY LMDB_INCLUDE_DIR)
