name: Build MapCache
on: [ push ]

jobs:

    build-default-on-bionic:
      runs-on: ubuntu-18.04
      steps:
        - name: Checkout MapCache repository
          uses: actions/checkout@v2

        - name: Install default dependencies
          run: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -y libcurl4-openssl-dev apache2-dev libgdal-dev libfcgi-dev

        - name: Build MapCache
          run: |
            mkdir build
            cd build
            cmake ${{ github.workspace }}
            make
            sudo make install

    build-maximum-on-bionic:
      runs-on: ubuntu-18.04
      steps:
        - name: Checkout MapCache repository
          uses: actions/checkout@v2

        - name: Install default dependencies
          run: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -y libcurl4-openssl-dev apache2-dev libgdal-dev libfcgi-dev

        - name: Install more dependencies
          run |
            sudo apt-get install -y libvibe-redis-dev libdb-dev libmapserver-dev

        - name: Install RIAK dependency
          run |
            curl http://apt.basho.com/gpg/basho.apt.key | sudo apt-key add -
            sudo bash -c "echo deb http://apt.basho.com `lsb_release -sc` main > /etc/apt/sources.list.d/basho.list"
            sudo apt-get update -y
            sudo apt-get install -y riak-dev

        - name: Build MapCache
          run: |
            mkdir build
            cd build
            cmake -DWITH_POSTGRESQL=ON \
                  -DWITH_BERKELEY_DB=ON \
                  -DWITH_MEMCACHE=ON \
                  -DWITH_REDIS=ON \
                  -DWITH_TIFF=ON \
                  -DWITH_TIFF_WRITE_SUPPORT=ON \
                  -DWITH_GEOTIFF=ON \
                  -DWITH_PCRE=ON \
                  -DWITH_MAPSERVER=ON \
                  -DWITH_RIAK=ON \
                  ${{ github.workspace }}
            make
            sudo make install


