name: Build MapCache
on: [ push ]

jobs:

    build-on-bionic:
      runs-on: ubuntu-18.04
      steps:
        - name: Checkout MapCache repository
          uses: actions/checkout@v2

        - run: mkdir build
        - run: cd build
        - run: cmake ${{ github.workspace }}
        - run: make


